language: python
sudo: false
python:
- '2.7'
- '3.6'
- '3.7'
- '3.8'
install:
  - echo ok
script:
  - echo ok
deploy:
  provider: pypi
  user: sensoranalytics
  password:
    secure: GWoOT5sTvCixxfmasFzWB8gfm0DSTfvsVdeYSWbLtoMy4Iti/dwnoj6D45Np7yQuppyjD4CR+1RO4IVuovFMcB5NKtXu4/1eYv+RspHFEsAKumwBeXrJ1kk45rWLlpgS1MDl6fVmZXU0Iz4xNs9AGVEpAtp3bkT3PfT9FcbLjak6rXVCH1wgZ9WE9kwsiIAmISg9Cs2bxGBSR2CqktcZjMZMaEyCNuuVnrfb4wGthQVp47GiOSV4avVeJdyt0VFHaQ4wlalnh/HkGvttIxG2a3nYAZRChwKhQAjgQZtul1KvMFRROCeDxyB/8a2F1YKCT0tPnk3mge0P7FONXlA8p4c5fNZUc+zgxmykMLjR5/LBNMogcvva3D/dRH7GV5XcL6mKFRmeIxv7g6AvonO1HRsJ5VVP0FBKjaj8YqVZ4Fc/XYSP8jToco5ThplOJSNnpeD7uN7+e6PIBvyVOoLj/b9oPSG3ArBYBTSVWaKqHtJT0mBYnEldRmmSPocVjtPdhfrewWljwzQh1SUoD+ScOwxg7nIAC7LM6V3FrRIEXIgTIxsY9ilS7vgrFI5F6KStvRhPAI48TLQtt6lDtmXfADpczBcWqnsTNMwH/NM0TTNBfN/mhwa4je/pknQLpaGjkuGLRgOO8LxlCihXSx5DVufkgzDn241DovrysFe0vaY=
  server: https://pypi.xiachufang.com
  distributions: sdist bdist_wheel
  on:
    repo: xiachufang/sensorsanalytics
